"""Stable public extension surface for independent BrainAgent domains."""

from domain_sdk.adapters import DomainSkillBridge
from domain_sdk.agent_dna import (
    AgentDnaDefinition,
    AgentDnaError,
    AgentPolicyProfile,
    PersistentAgentDnaRecord,
    PersistentAgentDnaRegistry,
    WorkflowDnaReference,
)
from domain_sdk.compatibility import (
    CompatibilityError,
    CompatibilityReport,
    assert_schema_backward_compatible,
    public_api_manifest,
    require_version,
)
from domain_sdk.composition import Application, CompositionRoot
from domain_sdk.contracts import (
    CapabilityContract,
    DomainPlugin,
    LoopProfile,
    OutcomeEvaluator,
    PluginContribution,
    SideEffect,
    SkillAdapter,
    SkillManifest,
    SkillRegistration,
    WorkflowRegistration,
)
from domain_sdk.dna import DnaDefinition, DnaError, DnaParent, DnaRegistry, DnaStatus
from domain_sdk.dna_candidates import (
    CandidateMode,
    CandidateOperation,
    CandidateOperationKind,
    CandidatePolicy,
    CandidateProposal,
    CandidateRequest,
    DnaCandidateError,
    DnaCandidateGenerator,
)
from domain_sdk.dna_composer import (
    CompositionLimits,
    CompositionMode,
    DnaComponent,
    DnaComposer,
    DnaCompositionError,
)
from domain_sdk.dna_explain import (
    DnaExplainError,
    DnaLineageExplainer,
    EvolutionExplanation,
    ExplainRequest,
)
from domain_sdk.dna_fitness import (
    DnaFitnessError,
    DnaFitnessObservation,
    DnaFitnessPolicy,
    DnaFitnessProjector,
    DnaFitnessSnapshot,
    FitnessReadiness,
)
from domain_sdk.dna_promotion import (
    DnaPromotionController,
    DnaPromotionError,
    PromotionCampaign,
    PromotionObservation,
    PromotionPolicy,
    PromotionRequest,
    PromotionRoute,
    PromotionStage,
)
from domain_sdk.dna_replay import (
    DnaReplayError,
    DnaSandboxReplay,
    FaultScenario,
    ReplayCase,
    ReplayContext,
    ReplayMeasurement,
    ReplayPolicy,
    ReplayReport,
    ReplayRequest,
    ReplayStatus,
    ReplayVector,
    SandboxExecutor,
)
from domain_sdk.dna_repository import PersistentDnaRecord, PersistentDnaRegistry
from domain_sdk.dna_selection import (
    DnaPopulationSelector,
    DnaSelectionError,
    PopulationCandidate,
    SelectionDisposition,
    SelectionMember,
    SelectionPolicy,
    SelectionReport,
    SelectionRequest,
)
from domain_sdk.experience_dataset import (
    DatasetCohort,
    DatasetSplit,
    ExperienceDataset,
    ExperienceDatasetBuilder,
    ExperienceDatasetError,
    ExperienceDatasetManifest,
    ExperienceDatasetSpec,
    ExperienceSample,
)
from domain_sdk.factor_loop import (
    FactorDiscoveryLoop,
    FactorLoopCheckpoint,
    FactorLoopProfile,
    FactorLoopStatus,
)
from domain_sdk.organization_dna import (
    ArbitrationStrategy,
    DelegationStrategy,
    OrganizationDnaDefinition,
    OrganizationDnaError,
    OrganizationMember,
    OrganizationPolicyProfile,
    PersistentOrganizationDnaRecord,
    PersistentOrganizationDnaRegistry,
)
from domain_sdk.organization_execution import (
    OrganizationExecutionRequest,
    OrganizationExecutionResult,
    OrganizationGovernedApp,
)
from domain_sdk.registry import PluginCatalog, PluginValidationError
from domain_sdk.runtime import RuntimeBuilder

__version__ = "0.1.0.dev0"

__all__ = [
    "AgentDnaDefinition",
    "AgentDnaError",
    "AgentPolicyProfile",
    "Application",
    "ArbitrationStrategy",
    "CandidateMode",
    "CandidateOperation",
    "CandidateOperationKind",
    "CandidatePolicy",
    "CandidateProposal",
    "CandidateRequest",
    "CapabilityContract",
    "CompatibilityError",
    "CompatibilityReport",
    "CompositionLimits",
    "CompositionMode",
    "CompositionRoot",
    "DatasetCohort",
    "DatasetSplit",
    "DelegationStrategy",
    "DnaCandidateError",
    "DnaCandidateGenerator",
    "DnaComponent",
    "DnaComposer",
    "DnaCompositionError",
    "DnaDefinition",
    "DnaError",
    "DnaExplainError",
    "DnaFitnessError",
    "DnaFitnessObservation",
    "DnaFitnessPolicy",
    "DnaFitnessProjector",
    "DnaFitnessSnapshot",
    "DnaLineageExplainer",
    "DnaParent",
    "DnaPopulationSelector",
    "DnaPromotionController",
    "DnaPromotionError",
    "DnaRegistry",
    "DnaReplayError",
    "DnaSandboxReplay",
    "DnaSelectionError",
    "DnaStatus",
    "DomainPlugin",
    "DomainSkillBridge",
    "EvolutionExplanation",
    "ExperienceDataset",
    "ExperienceDatasetBuilder",
    "ExperienceDatasetError",
    "ExperienceDatasetManifest",
    "ExperienceDatasetSpec",
    "ExperienceSample",
    "ExplainRequest",
    "FactorDiscoveryLoop",
    "FactorLoopCheckpoint",
    "FactorLoopProfile",
    "FactorLoopStatus",
    "FaultScenario",
    "FitnessReadiness",
    "LoopProfile",
    "OrganizationDnaDefinition",
    "OrganizationDnaError",
    "OrganizationExecutionRequest",
    "OrganizationExecutionResult",
    "OrganizationGovernedApp",
    "OrganizationMember",
    "OrganizationPolicyProfile",
    "OutcomeEvaluator",
    "PersistentAgentDnaRecord",
    "PersistentAgentDnaRegistry",
    "PersistentDnaRecord",
    "PersistentDnaRegistry",
    "PersistentOrganizationDnaRecord",
    "PersistentOrganizationDnaRegistry",
    "PluginCatalog",
    "PluginContribution",
    "PluginValidationError",
    "PopulationCandidate",
    "PromotionCampaign",
    "PromotionObservation",
    "PromotionPolicy",
    "PromotionRequest",
    "PromotionRoute",
    "PromotionStage",
    "ReplayCase",
    "ReplayContext",
    "ReplayMeasurement",
    "ReplayPolicy",
    "ReplayReport",
    "ReplayRequest",
    "ReplayStatus",
    "ReplayVector",
    "RuntimeBuilder",
    "SandboxExecutor",
    "SelectionDisposition",
    "SelectionMember",
    "SelectionPolicy",
    "SelectionReport",
    "SelectionRequest",
    "SideEffect",
    "SkillAdapter",
    "SkillManifest",
    "SkillRegistration",
    "WorkflowDnaReference",
    "WorkflowRegistration",
    "assert_schema_backward_compatible",
    "public_api_manifest",
    "require_version",
]
